name: Deploy Frontend.

on:

  push:

    branches: ["main"]

   

  workflow_dispatch:

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

 

    steps:

      - uses: actions/checkout@v3

 

 

      - name: SSH and Git Pull

        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.TEST_HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SERVER_KEY }}

          port: ${{ secrets.TEST_PORT }}

          script: |
            echo "Successfully ssh into Staging Server"
            echo "Setting up Git credentials for the pull"
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git config --global credential.helper store
            echo "machine github.com login ${{ secrets.GIT_TOKEN }} password x-oauth-basic" > ~/.netrc
            echo "Pulling the updated commit into the server"
            cd ~/solarps-blinks
            git checkout main
            git pull origin main
 

      - name: SSH into server and build Docker image.

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.TEST_HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SERVER_KEY }}

          port: ${{ secrets.TEST_PORT }}

          script: |
            cd ~/solarps-blinks
            sudo docker stop test || true
            sudo docker rm -f test || true
            sudo docker build -t test .
   

      - name: SSH into server and start Docker container

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.TEST_HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SERVER_KEY }}

          port: ${{ secrets.TEST_PORT }}

          script: |
            cd ~/solarps-blinks
            sudo docker build -t test .
            sudo docker run -d --name test -p 3000:3000 test
